spring:
  application:
    name: spring-boot-admin
  boot:
    admin:
      ui:
        public-url: http://spring-boot-admin.default.apps.example.com
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        service-labels: 
          tanzu.app.live.view.application.flavours: spring-boot

management:
  endpoints:
    web:
      exposure:
        include: "*"